### ISSUE TITLE
老哥做完了吗？

### ISSUE THREAD

**Issue by South-River** [FranHawk/simplefoc_balance_car#1]
做的咋样，发个视频？我等过两周考完试也开干，零件都到齐了2333

**Comment by FranHawk** [comment]
做完了，发到b站上了

**Comment by South-River** [comment]
哈哈哈厉害，我发现咱俩的长的几乎一样，很巧

**Comment by South-River** [comment]
不会你是看了我寒假发的半成品视频吧😂。厉害，👍

**Comment by FranHawk** [comment]
我也是寒假开始做的，可以给个视频链接吗，我还没看过你做的

**Comment by South-River** [comment]
2333我上周删了，没事没事

**Comment by South-River** [comment]
哈哈想起来又去翻了翻相册，确实很巧2333，都用的rc轮胎，外形设计也挺像∠( ᐛ 」∠)_
![Screenshot_2022-06-08-02-53-37-878_com.mxtech.videoplayer.ad.jpg](https://user-images.githubusercontent.com/52597530/172460357-7a9718e5-1489-4eaa-8cfc-7da749bd3d6c.jpg)
![-556f9374b426e952.jpg](https://user-images.githubusercontent.com/52597530/172460654-b81fc582-b586-4335-9fa4-61e6fcfc1ca4.jpg)
